const { defineConfig } = require("cypress");

module.exports = defineConfig({
  defaultCommandTimeout: 40000,
  pageLoadTimeout: 300000,
  includeShadowDom: true,
  env: {
    accessToken:
      "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlQxU3QtZExUdnlXUmd4Ql82NzZ1OGtyWFMtSSIsImtpZCI6IlQxU3QtZExUdnlXUmd4Ql82NzZ1OGtyWFMtSSJ9.eyJhdWQiOiJodHRwczovL3N3ZGV2cWFydXd5eHFhaGRzLXN3aWZ0Y2FyZWZoaXIuZmhpci5henVyZWhlYWx0aGNhcmVhcGlzLmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2MwY2Y5MzU4LTViM2UtNGIyYS04MTllLTQyNzE1MjIwOWE1MS8iLCJpYXQiOjE3MDE3ODc1NTgsIm5iZiI6MTcwMTc4NzU1OCwiZXhwIjoxNzAxNzkyMDMyLCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFZBQUFBS1c1aWw2dHNJZWtzVUw4a3V4Y3ozRS9SdkpCRnhrczNBVDRteURjbDVYbFFYcVNOdlBpVFBLZU1kZTVRTkZYUG4vNGw1RjBWR0RBMVl2ZHNGSjAwQjI0a1dWSmlvQU5rUkFFTHVBZUN2Smc9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjQ3YWFlYjNjLWNiNzgtNGIxNy04ZGFiLTA0ZTgyNTQ1YTg2MyIsImFwcGlkYWNyIjoiMSIsImZhbWlseV9uYW1lIjoiZmFoZWVtdGVzdCIsImdpdmVuX25hbWUiOiJmYWhlZW10ZXN0IiwiaXBhZGRyIjoiNTIuMjA3LjI0MC4xMDQiLCJuYW1lIjoiZmFoZWVtdGVzdCBNdWJhc2hlcnIiLCJvaWQiOiI4YTY0ZGRmZS1iNDVlLTRiNzAtYjIzMC1jOWMzN2ZlMTgwNzAiLCJwdWlkIjoiMTAwMzIwMDMxRjQ0MDc0NCIsInJoIjoiMC5BUTBBV0pQUHdENWJLa3VCbmtKeFVpQ2FVZGg0WjBfdld0eERvZi13YzNKTGxKVU5BTjguIiwic2NwIjoicGF0aWVudC5hbGwucmVhZCB1c2VyX2ltcGVyc29uYXRpb24iLCJzdWIiOiJ0NHVKaGRLZkI3b3BuSWlSektKSk1VcUYyMVg0dnVrMEthN1pqeXZsU2dnIiwidGlkIjoiYzBjZjkzNTgtNWIzZS00YjJhLTgxOWUtNDI3MTUyMjA5YTUxIiwidW5pcXVlX25hbWUiOiJmYWhlZW10ZXN0QHN3aWZ0bWVkaWNhbC5jb20iLCJ1cG4iOiJmYWhlZW10ZXN0QHN3aWZ0bWVkaWNhbC5jb20iLCJ1dGkiOiJpbG1lR2pWX3EwYTltMEVTbWRRcEFBIiwidmVyIjoiMS4wIn0.fJIiyFGL4LNCGO_t-lH-csBS-ss4NXiMwySdR0UaUVoH3QPmADKxyYJVg75bZJENnnueVuZbKIHLeoh1myphz1J_JLvqajCEzYHoYGfGExbz_59Xgf-zUmyBVbc6rgoT0hCBUNjVBTlcgY36RmalIEnmIkTERBCa84e_rckHft6XfJy2nHFfdGkLmZm_rBRqgy5wV0_d3R1vVvohnAxNwK3L0OileCKTuCAAfZ7l3H2pDTWwntVUrVaohJcJFfGAhRzL5z41Xkjy3OhCZdwHQwwwwEoYjDNck4dJjUJjkkivLyUZZjmNjjZlSVZgg6AESR1i0JjUYO3hhtTble6GAQ",
  },
  e2e: {
    baseUrl: "https://apollo-qa.swiftmedicalonline.com",
    specPattern: ["cypress/tests/*.js"],
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});
